/**
 * Pure planner for the HubSpot → EvoHome notes / inbound-engagement workstream.
 * Distinct from lead create/update. No I/O. Never include PII in reports.
 */

import { createHash } from "node:crypto";

import { stripHtmlToPlainText } from "@/lib/campaign-email";
import {
  envFlagEnabled,
  parseHubSpotOngoingSyncReleaseGate,
  type HubSpotSyncCursorStatus,
  type HubSpotSyncMutationDecision,
} from "@/lib/hubspot-ongoing-sync";

export const HUBSPOT_NOTES_SYNC_INTELLIGENCE_SOURCE = "hubspot_notes_sync";

export const HUBSPOT_NOTE_IDEMPOTENCY_PREFIX = "hubspot:note:";

export const HUBSPOT_NOTES_SYNC_SIDE_EFFECT_GUARD = Object.freeze({
  triggerAutomation: false,
  enrollCampaigns: false,
  enrollDrips: false,
  mutateLeadProject: false,
  mutateLeadStatus: false,
  mutateLeadSource: false,
});

export const HUBSPOT_NOTE_KINDS = ["note", "inbound_email", "form_submission"] as const;
export type HubSpotNoteKind = (typeof HUBSPOT_NOTE_KINDS)[number];

export const HUBSPOT_NOTE_ACTIVITY_TYPE_KEYS = {
  note: "note",
  inbound_email: "email",
  form_submission: "note",
} as const;

export const HUBSPOT_NOTE_PROPERTIES = [
  "hs_note_body",
  "hs_timestamp",
  "hs_lastmodifieddate",
  "hs_attachment_ids",
  "hubspot_owner_id",
  "hs_body_preview",
  "hs_created_by_user_id",
  "hs_object_source",
] as const;

export const HUBSPOT_EMAIL_PROPERTIES = [
  "hs_email_text",
  "hs_email_html",
  "hs_email_direction",
  "hs_email_subject",
  "hs_timestamp",
  "hs_lastmodifieddate",
  "hs_email_from_email",
  "hs_email_sender_email",
  "hs_email_status",
  "hs_email_to_email",
  "hs_object_source",
] as const;

const INCLUDED_EMAIL_DIRECTIONS = new Set([
  "INCOMING",
  "INCOMING_EMAIL",
  "INCOMING_EMAIL_REPLY",
]);

const EXCLUDED_OBJECT_SOURCES = new Set([
  "AUTOMATION_PLATFORM",
  "WORKFLOWS",
  "SEQUENCES",
  "IMPORT",
  "CRM_UI_BULK_ACTION",
  "INTEGRATION",
  "MIGRATION",
]);

const EXCLUDED_FROM_PATTERNS = [
  /(?:^|@)hubspot\.com$/i,
  /mailer-daemon/i,
  /no-?reply@/i,
  /notifications?@/i,
  /bounce@/i,
  /postmaster@/i,
];

const EXCLUDED_BODY_PATTERNS = [
  /this (?:note|email|message) was (?:automatically )?generated/i,
  /generated by (?:a )?hubspot (?:workflow|sequence|automation)/i,
  /sent (?:automatically )?by hubspot/i,
  /\[internal(?:\s+only)?\]/i,
  /hubspot(?:\s+crm)? system (?:note|message)/i,
  /do not reply to this (?:email|message)/i,
];

const MAX_TITLE_LENGTH = 200;
const MAX_BODY_LENGTH = 5000;

export type HubSpotTimelineItem = {
  externalActivityId: string;
  kind: HubSpotNoteKind | "outbound_email" | "task" | "call" | "meeting" | "unknown";
  contactId: string;
  occurredAt: string | null;
  lastModifiedAt: string | null;
  sourceLabel: string | null;
  formLabel: string | null;
  subject: string | null;
  bodyHtml: string | null;
  bodyText: string | null;
  direction: string | null;
  objectSource: string | null;
  fromEmail: string | null;
};

export type HubSpotNoteExclusionReason =
  | "empty_body"
  | "internal_system_noise"
  | "automation_source"
  | "outbound_email"
  | "unsupported_kind"
  | "internal_sender";

export type HubSpotNoteClassification =
  | { include: true; kind: HubSpotNoteKind }
  | { include: false; reason: HubSpotNoteExclusionReason };

export type HubSpotNoteIdentityDecision =
  | { kind: "match"; leadId: string; method: "hubspot_contact_id" | "unique_email" }
  | { kind: "park"; reason: "lead_not_found" | "email_ambiguous" };

export type HubSpotNoteActivityPlan = {
  externalActivityId: string;
  idempotencyKey: string;
  activityTypeKey: "note" | "email";
  title: string;
  description: string;
  occurredAt: string;
  sourceLabel: string | null;
  formLabel: string | null;
  provenance: {
    source: typeof HUBSPOT_NOTES_SYNC_INTELLIGENCE_SOURCE;
    kind: HubSpotNoteKind;
    hubspotContactId: string;
    externalActivityId: string;
    sourceOccurredAt: string;
    sourceLabel: string | null;
    formLabel: string | null;
  };
  triggerAutomation: false;
  mutateLeadProject: false;
  mutateLeadStatus: false;
};

export function assertHubSpotNotesSideEffectGuard(
  guard: typeof HUBSPOT_NOTES_SYNC_SIDE_EFFECT_GUARD = HUBSPOT_NOTES_SYNC_SIDE_EFFECT_GUARD,
): void {
  if (
    guard.triggerAutomation !== false ||
    guard.enrollCampaigns !== false ||
    guard.enrollDrips !== false
  ) {
    throw new Error("notes_side_effect_guard:campaign_enrollment_forbidden");
  }
  if (guard.mutateLeadProject || guard.mutateLeadStatus || guard.mutateLeadSource) {
    throw new Error("notes_side_effect_guard:lead_mutation_forbidden");
  }
}

export function evaluateHubSpotNotesMutationGate(input: {
  releaseGate?: string | null;
  incrementalEnabled?: string | null;
  backfillEnabled?: string | null;
  path: "incremental" | "backfill" | "dry-run";
  notesStatus?: HubSpotSyncCursorStatus | null;
  notesDryRunVerifiedAt?: Date | string | null;
}): HubSpotSyncMutationDecision {
  const releaseGate = parseHubSpotOngoingSyncReleaseGate(input.releaseGate);
  const ledger = true;

  if (releaseGate === "off") {
    return { ledger, plan: false, mutate: false, reason: "release_gate_off" };
  }

  if (releaseGate === "dry-run" || input.path === "dry-run") {
    return { ledger, plan: true, mutate: false, reason: "release_gate_dry_run" };
  }

  if (input.path === "incremental" && !envFlagEnabled(input.incrementalEnabled)) {
    return { ledger, plan: true, mutate: false, reason: "notes_incremental_disabled" };
  }

  if (input.path === "backfill" && !envFlagEnabled(input.backfillEnabled)) {
    return { ledger, plan: true, mutate: false, reason: "notes_backfill_disabled" };
  }

  if (input.notesStatus === "paused") {
    return { ledger, plan: true, mutate: false, reason: "cursor_paused" };
  }

  if (input.notesStatus !== "active") {
    return { ledger, plan: true, mutate: false, reason: "cursor_not_active" };
  }

  if (!input.notesDryRunVerifiedAt) {
    return { ledger, plan: true, mutate: false, reason: "dry_run_not_verified" };
  }

  return { ledger, plan: true, mutate: true, reason: "mutate_allowed" };
}

export function hubspotNoteIdempotencyKey(externalActivityId: string): string {
  return `${HUBSPOT_NOTE_IDEMPOTENCY_PREFIX}${String(externalActivityId).trim()}`;
}

export function hubspotNoteEventKey(input: {
  externalActivityId: string;
  lastModifiedAt?: string | null;
}): string {
  const modified = input.lastModifiedAt?.trim() || "na";
  return `hubspot:note-event:${String(input.externalActivityId).trim()}:${modified}`;
}

export function sanitizeHubSpotNoteText(value: string | null | undefined): string {
  const raw = String(value ?? "");
  const stripped = stripHtmlToPlainText(raw)
    .replace(/\u0000/g, "")
    .replace(/[ \t]+\n/g, "\n")
    .trim();
  if (stripped.length <= MAX_BODY_LENGTH) {
    return stripped;
  }
  return `${stripped.slice(0, MAX_BODY_LENGTH - 1).trimEnd()}…`;
}

function normalizeSource(value: string | null | undefined): string {
  return String(value ?? "")
    .trim()
    .toUpperCase()
    .replace(/[\s-]+/g, "_");
}

export function classifyHubSpotTimelineItem(
  item: HubSpotTimelineItem,
): HubSpotNoteClassification {
  const kind = item.kind;
  if (kind === "outbound_email" || kind === "task" || kind === "call" || kind === "meeting") {
    return { include: false, reason: kind === "outbound_email" ? "outbound_email" : "unsupported_kind" };
  }
  if (kind === "unknown") {
    return { include: false, reason: "unsupported_kind" };
  }

  const objectSource = normalizeSource(item.objectSource);
  if (objectSource && EXCLUDED_OBJECT_SOURCES.has(objectSource)) {
    return { include: false, reason: "automation_source" };
  }

  if (kind === "inbound_email") {
    const direction = normalizeSource(item.direction);
    if (direction && !INCLUDED_EMAIL_DIRECTIONS.has(direction)) {
      return { include: false, reason: "outbound_email" };
    }
    const fromEmail = String(item.fromEmail ?? "").trim();
    if (fromEmail && EXCLUDED_FROM_PATTERNS.some((pattern) => pattern.test(fromEmail))) {
      return { include: false, reason: "internal_sender" };
    }
  }

  const body = sanitizeHubSpotNoteText(item.bodyText || item.bodyHtml);
  if (!body) {
    return { include: false, reason: "empty_body" };
  }
  if (EXCLUDED_BODY_PATTERNS.some((pattern) => pattern.test(body))) {
    return { include: false, reason: "internal_system_noise" };
  }

  return { include: true, kind };
}

export function resolveHubSpotNotesLeadMatch(input: {
  byContactIdLeadId?: string | null;
  emailCandidateLeadIds?: string[];
}): HubSpotNoteIdentityDecision {
  const byContact = input.byContactIdLeadId?.trim();
  if (byContact) {
    return { kind: "match", leadId: byContact, method: "hubspot_contact_id" };
  }
  const unique = [...new Set((input.emailCandidateLeadIds ?? []).filter(Boolean))];
  if (unique.length === 1) {
    return { kind: "match", leadId: unique[0], method: "unique_email" };
  }
  if (unique.length > 1) {
    return { kind: "park", reason: "email_ambiguous" };
  }
  return { kind: "park", reason: "lead_not_found" };
}

function clipTitle(value: string): string {
  const trimmed = value.trim().replace(/\s+/g, " ");
  if (trimmed.length <= MAX_TITLE_LENGTH) {
    return trimmed;
  }
  return `${trimmed.slice(0, MAX_TITLE_LENGTH - 1).trimEnd()}…`;
}

export function planHubSpotNoteActivity(item: HubSpotTimelineItem): HubSpotNoteActivityPlan | null {
  const classified = classifyHubSpotTimelineItem(item);
  if (!classified.include) {
    return null;
  }

  const body = sanitizeHubSpotNoteText(item.bodyText || item.bodyHtml);
  const occurredAt =
    item.occurredAt && !Number.isNaN(Date.parse(item.occurredAt))
      ? new Date(item.occurredAt).toISOString()
      : new Date(0).toISOString();

  const sourceLabel =
    item.sourceLabel?.trim() ||
    (classified.kind === "form_submission"
      ? "HubSpot form"
      : classified.kind === "inbound_email"
        ? "HubSpot inbound email"
        : "HubSpot note");
  const formLabel = item.formLabel?.trim() || null;
  const subject = item.subject?.trim() || null;

  const title = clipTitle(
    classified.kind === "form_submission"
      ? formLabel
        ? `Form: ${formLabel}`
        : "HubSpot form submission"
      : classified.kind === "inbound_email"
        ? subject
          ? `Inbound email: ${subject}`
          : "HubSpot inbound email"
        : sourceLabel === "HubSpot note"
          ? "HubSpot note"
          : `HubSpot note · ${sourceLabel}`,
  );

  const header = [sourceLabel, formLabel && formLabel !== sourceLabel ? formLabel : null]
    .filter(Boolean)
    .join(" · ");
  const description = header ? `${header}\n\n${body}` : body;

  return {
    externalActivityId: item.externalActivityId,
    idempotencyKey: hubspotNoteIdempotencyKey(item.externalActivityId),
    activityTypeKey: HUBSPOT_NOTE_ACTIVITY_TYPE_KEYS[classified.kind],
    title,
    description: description.length > MAX_BODY_LENGTH ? `${description.slice(0, MAX_BODY_LENGTH - 1)}…` : description,
    occurredAt,
    sourceLabel,
    formLabel,
    provenance: {
      source: HUBSPOT_NOTES_SYNC_INTELLIGENCE_SOURCE,
      kind: classified.kind,
      hubspotContactId: item.contactId,
      externalActivityId: item.externalActivityId,
      sourceOccurredAt: occurredAt,
      sourceLabel,
      formLabel,
    },
    triggerAutomation: false,
    mutateLeadProject: false,
    mutateLeadStatus: false,
  };
}

export function mapHubSpotNoteObjectToTimelineItem(input: {
  id: string;
  contactId: string;
  properties: Record<string, string | null | undefined>;
}): HubSpotTimelineItem {
  const body = input.properties.hs_note_body ?? input.properties.hs_body_preview ?? null;
  return {
    externalActivityId: `note:${input.id}`,
    kind: "note",
    contactId: input.contactId,
    occurredAt: input.properties.hs_timestamp ?? null,
    lastModifiedAt: input.properties.hs_lastmodifieddate ?? null,
    sourceLabel: "HubSpot note",
    formLabel: null,
    subject: null,
    bodyHtml: body,
    bodyText: body,
    direction: null,
    objectSource: input.properties.hs_object_source ?? null,
    fromEmail: null,
  };
}

export function mapHubSpotEmailObjectToTimelineItem(input: {
  id: string;
  contactId: string;
  properties: Record<string, string | null | undefined>;
}): HubSpotTimelineItem {
  const direction = input.properties.hs_email_direction ?? null;
  const incoming = INCLUDED_EMAIL_DIRECTIONS.has(normalizeSource(direction));
  return {
    externalActivityId: `email:${input.id}`,
    kind: incoming ? "inbound_email" : "outbound_email",
    contactId: input.contactId,
    occurredAt: input.properties.hs_timestamp ?? null,
    lastModifiedAt: input.properties.hs_lastmodifieddate ?? null,
    sourceLabel: incoming ? "HubSpot inbound email" : "HubSpot email",
    formLabel: null,
    subject: input.properties.hs_email_subject ?? null,
    bodyHtml: input.properties.hs_email_html ?? null,
    bodyText: input.properties.hs_email_text ?? null,
    direction,
    objectSource: input.properties.hs_object_source ?? null,
    fromEmail: input.properties.hs_email_from_email ?? input.properties.hs_email_sender_email ?? null,
  };
}

export function mapHubSpotFormMessageToTimelineItem(input: {
  contactId: string;
  message: string | null | undefined;
  formLabel?: string | null;
  occurredAt?: string | null;
}): HubSpotTimelineItem | null {
  const body = sanitizeHubSpotNoteText(input.message);
  if (!body) {
    return null;
  }
  const occurredAt = input.occurredAt ?? null;
  const fingerprint = createHash("sha256").update(`${input.contactId}:${occurredAt ?? ""}:${body}`).digest("hex").slice(0, 16);
  return {
    externalActivityId: `form-message:${input.contactId}:${fingerprint}`,
    kind: "form_submission",
    contactId: input.contactId,
    occurredAt,
    lastModifiedAt: occurredAt,
    sourceLabel: "HubSpot form",
    formLabel: input.formLabel?.trim() || null,
    subject: null,
    bodyHtml: input.message ?? null,
    bodyText: body,
    direction: null,
    objectSource: "FORM",
    fromEmail: null,
  };
}

export function hubspotContactIdFromLeadAttributes(
  attributes: Record<string, unknown> | null | undefined,
): string | null {
  if (!attributes || typeof attributes !== "object") {
    return null;
  }
  const raw = attributes.integration;
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    return null;
  }
  const integration = raw as Record<string, unknown>;
  if (typeof integration.externalId === "string" && integration.externalId.trim()) {
    return integration.externalId.trim();
  }
  if (
    typeof integration.idempotencyKey === "string" &&
    integration.idempotencyKey.startsWith("hubspot:contact:")
  ) {
    const id = integration.idempotencyKey.slice("hubspot:contact:".length).trim();
    return id || null;
  }
  return null;
}

export function evaluateHubSpotNotesDryRun(input: {
  searched: boolean;
  contactsScanned: number;
}): { ok: true } | { ok: false; reason: "search_not_run" | "no_contacts_scanned" } {
  if (!input.searched) {
    return { ok: false, reason: "search_not_run" };
  }
  if (input.contactsScanned < 1) {
    return { ok: false, reason: "no_contacts_scanned" };
  }
  return { ok: true };
}
