import { describe, expect, it } from "vitest";

import {
  classifyHubSpotTimelineItem,
  evaluateHubSpotNotesDryRun,
  evaluateHubSpotNotesMutationGate,
  hubspotContactIdFromLeadAttributes,
  hubspotNoteIdempotencyKey,
  mapHubSpotEmailObjectToTimelineItem,
  mapHubSpotFormMessageToTimelineItem,
  planHubSpotNoteActivity,
  resolveHubSpotNotesLeadMatch,
  sanitizeHubSpotNoteText,
  type HubSpotTimelineItem,
} from "@/lib/hubspot-notes-sync";

function noteItem(overrides: Partial<HubSpotTimelineItem> = {}): HubSpotTimelineItem {
  return {
    externalActivityId: "note:1",
    kind: "note",
    contactId: "99",
    occurredAt: "2026-08-20T09:00:00.000Z",
    lastModifiedAt: "2026-08-20T09:00:00.000Z",
    sourceLabel: "HubSpot note",
    formLabel: null,
    subject: null,
    bodyHtml: "<p>Interested in a visit</p>",
    bodyText: "Interested in a visit",
    direction: null,
    objectSource: "CRM_UI",
    fromEmail: null,
    ...overrides,
  };
}

describe("HubSpot notes privacy and sanitization", () => {
  it("includes user notes, form messages, and inbound email; excludes internal/system noise", () => {
    expect(classifyHubSpotTimelineItem(noteItem())).toEqual({ include: true, kind: "note" });

    const form = mapHubSpotFormMessageToTimelineItem({
      contactId: "99",
      message: "Please call me about unit A",
      formLabel: "Website contact",
      occurredAt: "2026-08-20T09:00:00.000Z",
    });
    expect(form).not.toBeNull();
    expect(classifyHubSpotTimelineItem(form!)).toEqual({ include: true, kind: "form_submission" });

    const inbound = mapHubSpotEmailObjectToTimelineItem({
      id: "e1",
      contactId: "99",
      properties: {
        hs_email_direction: "INCOMING_EMAIL",
        hs_email_text: "Can we schedule a tour?",
        hs_email_subject: "Tour",
        hs_timestamp: "2026-08-20T10:00:00.000Z",
        hs_email_from_email: "ada@example.com",
      },
    });
    expect(classifyHubSpotTimelineItem(inbound)).toEqual({ include: true, kind: "inbound_email" });

    expect(
      classifyHubSpotTimelineItem(
        noteItem({ bodyText: "This note was automatically generated by a HubSpot workflow." }),
      ),
    ).toEqual({ include: false, reason: "internal_system_noise" });

    expect(
      classifyHubSpotTimelineItem(noteItem({ objectSource: "WORKFLOWS", bodyText: "Assigned owner" })),
    ).toEqual({ include: false, reason: "automation_source" });

    expect(
      classifyHubSpotTimelineItem(
        mapHubSpotEmailObjectToTimelineItem({
          id: "e2",
          contactId: "99",
          properties: {
            hs_email_direction: "EMAIL",
            hs_email_text: "Our brochure",
            hs_email_from_email: "sales@evo-home.ch",
          },
        }),
      ),
    ).toEqual({ include: false, reason: "outbound_email" });

    expect(
      classifyHubSpotTimelineItem(
        mapHubSpotEmailObjectToTimelineItem({
          id: "e3",
          contactId: "99",
          properties: {
            hs_email_direction: "INCOMING_EMAIL",
            hs_email_text: "bounce notice",
            hs_email_from_email: "mailer-daemon@hubspot.com",
          },
        }),
      ),
    ).toEqual({ include: false, reason: "internal_sender" });
  });

  it("sanitizes HTML to readable text and plans provenance without campaign side effects", () => {
    expect(sanitizeHubSpotNoteText("<p>Hello<br/>Ada</p><script>alert(1)</script>")).toBe("Hello\nAda");
    const planned = planHubSpotNoteActivity(noteItem({ bodyHtml: "<p>Interested in a visit</p>" }));
    expect(planned).toMatchObject({
      activityTypeKey: "note",
      title: "HubSpot note",
      triggerAutomation: false,
      mutateLeadProject: false,
      mutateLeadStatus: false,
      provenance: {
        hubspotContactId: "99",
        externalActivityId: "note:1",
        sourceOccurredAt: "2026-08-20T09:00:00.000Z",
      },
    });
    expect(planned?.description).toContain("Interested in a visit");
    expect(hubspotNoteIdempotencyKey("note:1")).toBe("hubspot:note:note:1");
  });
});

describe("HubSpot notes identity", () => {
  it("prefers HubSpot contact id and parks ambiguous email fallback", () => {
    expect(
      resolveHubSpotNotesLeadMatch({
        byContactIdLeadId: "lead-hs",
        emailCandidateLeadIds: ["lead-a", "lead-b"],
      }),
    ).toEqual({ kind: "match", leadId: "lead-hs", method: "hubspot_contact_id" });

    expect(
      resolveHubSpotNotesLeadMatch({
        byContactIdLeadId: null,
        emailCandidateLeadIds: ["lead-only"],
      }),
    ).toEqual({ kind: "match", leadId: "lead-only", method: "unique_email" });

    expect(
      resolveHubSpotNotesLeadMatch({
        byContactIdLeadId: null,
        emailCandidateLeadIds: ["lead-a", "lead-b"],
      }),
    ).toEqual({ kind: "park", reason: "email_ambiguous" });

    expect(
      hubspotContactIdFromLeadAttributes({
        integration: { idempotencyKey: "hubspot:contact:99", externalId: "99" },
      }),
    ).toBe("99");
  });
});

describe("HubSpot notes gates and dry-run", () => {
  it("defaults off and requires a searched dry-run with scanned contacts", () => {
    expect(evaluateHubSpotNotesMutationGate({ path: "incremental" })).toMatchObject({
      mutate: false,
      reason: "release_gate_off",
    });
    expect(
      evaluateHubSpotNotesMutationGate({
        releaseGate: "enabled",
        incrementalEnabled: "true",
        path: "incremental",
        notesStatus: "active",
        notesDryRunVerifiedAt: "2026-08-31T00:00:00.000Z",
      }),
    ).toMatchObject({ mutate: true, reason: "mutate_allowed" });

    expect(evaluateHubSpotNotesDryRun({ searched: false, contactsScanned: 4 })).toEqual({
      ok: false,
      reason: "search_not_run",
    });
    expect(evaluateHubSpotNotesDryRun({ searched: true, contactsScanned: 0 })).toEqual({
      ok: false,
      reason: "no_contacts_scanned",
    });
    expect(evaluateHubSpotNotesDryRun({ searched: true, contactsScanned: 2 })).toEqual({ ok: true });
  });
});
